-- =============================================================================
-- FUTEX Energy Solution — local seed (supabase db reset)
-- =============================================================================
-- Pricing (packages / enclosures / add-ons / settings) now lives in the
-- tracked migration 20260626000004_seed_pricing.sql so it also reaches
-- production via the GitHub -> Supabase integration. This file is intentionally
-- minimal; it runs after migrations on `supabase db reset`.
--
-- Demo USERS (one per role) + sample bookings need the Supabase auth admin API,
-- so they are created by the Node script instead:
--
--     npm run seed        # scripts/seed.ts  (uses SUPABASE_SERVICE_ROLE_KEY)
--
-- Nothing else to do here — pricing is already applied by the migration above.
-- =============================================================================
